# http://module-build.sourceforge.net/META-spec.html
name:         Geo-IP2Location
version:      8.51
version_from: lib/Geo/IP2Location.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
